#!/usr/bin/ksh
Tmp="/tmp/$$"
TmpDir="/tmp/dir$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15
rm $Tmp  >/dev/null 2>&1

adder() {
print "Running adder()"
cp $1 /home/mestes/.vim/bundle/$REPO/$1
if [ "$LOCAL" == "" ] ; then
     IP=192.168.1.1
     fping -c1 -t300 $IP 2>/dev/null 1>/dev/null

#     if [ $? -eq 0 ] ; then
      if [[ $? -eq 0 || $FORCE -eq 1 ]] ; then
          print "  add $1"
          git add $1
     else
          print "  network not available, add not performed"
     fi
fi
print "-"
}
updater() {
print "Running updater()"
if [ "$LOCAL" == "" ] ; then
     IP=192.168.1.1
     fping -c1 -t300 $IP 2>/dev/null 1>/dev/null
#    if [ $? -eq 0 ] ; then
     if [[ $? -eq 0 || $FORCE -eq 1 ]] ; then
          print "  commiting"
          git commit -m "Update"
          print "  pushing"
          git push -u origin master
     else
          print "  network not available, commit and push not performed"
     fi
fi
print "-"
}

# #######################################
REPO=vim-progsnips
LOCAL=""
while getopts "l" arg
do
	case $arg in
            l) LOCAL="yes" ;;
        esac
done
FORCE=1
ANON=`date`
print $ANON

adder plugin/test.txt
adder plugin/KSH.txt
adder pushit
adder README.md

adder plugin/Appl.txt
adder plugin/ex11.txt
adder plugin/Gawk.txt
adder plugin/Prim.txt
adder plugin/QuickClass.txt
adder plugin/Sb.txt
adder plugin/Scanner.txt
adder plugin/songs.txt
adder plugin/StaticVoidMain.txt
adder plugin/Switch.txt
adder plugin/SysOut.txt
adder plugin/Template.txt
adder plugin/Try.txt
adder plugin/Uni.txt
adder plugin/VarChar.txt
adder plugin/VarDouble.txt
adder plugin/VarFloat.txt
adder plugin/Varint.txt
adder plugin/VarString.txt
adder plugin/Var.txt

adder plugin/ex1.java
adder plugin/ex2.java
adder plugin/ex3.java
adder plugin/ex4.java
adder plugin/ex5a.java
adder plugin/ex5b.java
adder plugin/ex5bnew.java
adder plugin/ex5c.java
adder plugin/ex5d.java
adder plugin/ex6b.java
adder plugin/ex6.java
adder plugin/ex8.java
adder plugin/ex9.java
adder plugin/ex10.java
adder plugin/ex11.java
adder plugin/ex12a.java
adder plugin/ex12b.java
adder plugin/FileTest2.java
adder plugin/FileTest.java
adder plugin/forexamples.java
adder plugin/IntCircle.java
adder plugin/PlayList.java
adder plugin/PlayListTest.java
adder plugin/Scores.java
adder plugin/Song.java



updater

